#!/bin/bash

#author: Vadim M. Gumerov, 08/12/2019
#The scriprt processes csv files generated by Cytoscape:
# 1) Extracts protein ids
# 2) Mapps the ids on the newick tree
# 3) Extracts protein sequences from NCBI and MiST using the ids.
# 4) Extarct organism names from the file with protein sequence information generated at stage 3
# 5) Retrieves full taxonomy information for the proteins in clusters

PATH=$(pwd)

for everyFile in $PATH/*.ocls; do
	/bin/mkdir ${everyFile%.*}_ocls
	/bin/cp ${everyFile} ${everyFile%.*}_ocls
done


#~ 
for everyFolder in $PATH/*_ocls; do
	cd ${everyFolder}
	echo "===== Current folder" ${everyFolder%_*}
	/usr/bin/python ../mkdirsAndGetIdsFromClstOperons.py ${everyFolder%_*}.ocls
	for inFolder in geneContext*; do
		echo "Extracting protein sequences..."
		~/bin/prepareNamesAndFetch.py -i "${everyFolder}/${inFolder}/geneContext.ids" -o "${everyFolder}/${inFolder}/geneContext.fa" -f true -c 50;
		echo "Extracting organism names..."
		/bin/grep '>' "${everyFolder}/${inFolder}/geneContext.fa" | /usr/bin/cut -f 2 -d '['  | /bin/sed 's/]//' > "${everyFolder}/${inFolder}/geneContext_names.txt";
		echo "Retrieving taxonomy information..."
		~/bin/getFullTaxonomy.py "${everyFolder}/${inFolder}/geneContext_names.txt" GTDB > "${everyFolder}/${inFolder}/geneContext_taxonomy.txt"
		echo "Extracting sequences of gene neighbors"
		~/bin/extract_seqs_for_gene_neighbors.py -i $PATH/linsi_no_edited_ML_BS100.json -s "${everyFolder}/${inFolder}/geneContext.ids" -o "${everyFolder}/${inFolder}/geneContext.nfa" > /dev/null
		/bin/grep -v '========================================================================='  "${everyFolder}/${inFolder}/geneContext.nfa" | /bin/grep  -v ^[[:digit:]] > "${everyFolder}/${inFolder}/geneContext.fa"

		echo "======================================="
		echo " "
	done
	cd ..

done

echo "Finished"



















